### ISSUE TITLE
Error when trying to redeem

### ISSUE THREAD

**Issue by arsena21** [daostack/alchemy#708]
see screenshots:

http://prntscr.com/nopzjv
https://prnt.sc/nopyjn
http://prntscr.com/nopyq2

I tried a few times, nothing seems to happen other than get the error.

I'm not sure but it looks like this transaction? http://prntscr.com/noq4ve

**Comment by A-Zak** [comment]
this was resolved, right?

**Comment by jellegerbrandy** [comment]
Thanks for the error report, @arsena21 ... Your problem is that the transactions you sent did not get mined. That may be either because you set a low gas price (in metamask when you sent the transaction) or because the network as very busy. We cannot really do much about that except show a better error message.

Here is an issue for that: https://github.com/daostack/alchemy/issues/777

**Comment by arsena21** [comment]
Trying again:
1) http://prntscr.com/nx4gp5
2) confirming: http://prntscr.com/nx4h07
3) showing up in metamask: http://prntscr.com/nx4h79 
4) metamask shows confirmed: http://prntscr.com/nx4igz
5) proposal is still showing up in redemptions: http://prntscr.com/nx4iwk
